### ISSUE TITLE
JS console errors, event name not selectable, saving broken

### ISSUE THREAD

**Issue by riccardolardi** [craftcms/webhooks#42]
### Description

Upon pressing "new webhook" I get two JS errors in console and then I'm not able to choose event name nor save the webhook. Clicking save leads to 403 Forbidden error.

Console errors:

```
vue.js:6 TypeError: Cannot set property 'onInputChange' of undefined
    at wn.data (new:705)
    at wn.<anonymous> (vue.js:6)
    at vue.js:6
    at vue.js:6
    at vn (vue.js:6)
    at wn.t._init (vue.js:6)
    at new wn (vue.js:6)
    at new:697
```

```
ReferenceError: filteredOptions is not defined
    at wn.eval (eval at Ya (vue.js:6), <anonymous>:3:141)
    at wn.e._render (vue.js:6)
    at wn.r (vue.js:6)
    at fn.get (vue.js:6)
    at new fn (vue.js:6)
    at vue.js:6
    at wn.$mount (vue.js:6)
    at wn.$mount (vue.js:6)
    at wn.t._init (vue.js:6)
    at new wn (vue.js:6)
```

### Steps to reproduce

1. Click "new webhook"
2. See console errors
3. Hit "save"

### Additional info

- Craft version: Craft Solo 3.6.3
- PHP version: 7.3.26
- Database driver & version: MySQL
- Plugins & versions: Webhook 2.3.2

**Comment by carlcs** [comment]
I submitted a pull request earlier today that fixes this issue. https://github.com/craftcms/webhooks/pull/41

**Comment by angrybrad** [comment]
Fixed this in Craft 3.6.4. Sorry about that!

**Comment by riccardolardi** [comment]
The JS error is gone since Craft 3.6.4 but I still get a 403 error from the server once saving the webhook:

```
Forbidden
You don't have permission to access this resource.

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.
```

Is this related?
